### ISSUE TITLE
Bot responding incorrectly to !withdraw

### ISSUE THREAD

**Issue by CubityFirst** [Nicklason/tf2-automatic#309] opened 2020-02-23 18:33 UTC
Bot isn't responding to !withdraw, and telling me that it doesn't have the item that I'm questing
**To Reproduce**

1. ... Try to !withdraw a large quantity of metal. (!withdraw name=Refined Metal&amount=200)
2. ... Bot will tell you that they don't have the large quantity of item.
3. ... ? ? ?

**Expected behavior**
I expect it to give me the item.

**Screenshots and logs**

https://i.cubityfir.st/uu7cLRw8R
https://i.cubityfir.st/ETbCTRECSU
https://i.cubityfir.st/X6RiYFbb74

Version: 
3.0.2

**Comment by Nicklason** [comment] 2020-02-24 22:41
I can't reproduce this

**Comment by CubityFirst** [comment] 2020-02-25 08:53
Seemed to be an issue with the SteamAPI at the time, it was happening to everyone at that point, and I haven't heard it mentioned since.

This can get closed.

**Comment by Nicklason** [comment] 2020-02-25 08:56
Then just close it

**Closed by Nicklason** 2020-02-25 08:56 UTC
Labels: bug
