### ISSUE TITLE
Crash Unexpectedly

### ISSUE THREAD

**Issue by Doomy50** [Nicklason/tf2-automatic#15] opened 2018-08-02 09:31 UTC
This is the error code.

0|automati | 02-08-2018 03:24:54 - error: tf2-automatic crashed! Please create an issue with the following log:
0|automati | crash: Automatic.version: 1.7.23; node: v10.7.0 linux x64; Contact: 76561198840991984
0|automati | crash: Stack trace:
0|automati | ReferenceError: community is not defined
0|automati |     at sentOfferChanged (/root/tradebot/app/trade.js:1024:9)
0|automati |     at handleChangedOffers (/root/tradebot/app/trade.js:132:9)
0|automati |     at Object.exports.init (/root/tradebot/app/trade.js:55:5)
0|automati |     at ready (/root/tradebot/app/client.js:114:11)
0|automati |     at /root/tradebot/node_modules/async/dist/async.js:3888:9
0|automati |     at /root/tradebot/node_modules/async/dist/async.js:473:16
0|automati |     at replenish (/root/tradebot/node_modules/async/dist/async.js:1006:25)
0|automati |     at iterateeCallback (/root/tradebot/node_modules/async/dist/async.js:995:17)
0|automati |     at /root/tradebot/node_modules/async/dist/async.js:969:16
0|automati |     at /root/tradebot/node_modules/async/dist/async.js:3885:13
0|automati | 02-08-2018 03:24:54 - error: Create an issue here: https://github.com/Nicklason/tf2-automatic/issues/new

**Comment by ZeusJunior** [comment] 2018-08-02 09:32
duplicate of #13

**Closed** 2018-08-02 09:35 UTC
Labels: duplicate
