### ISSUE TITLE
Name Tag sku problem

### ISSUE THREAD

**Issue by Atosito** [Nicklason/tf2-automatic#347] opened 2020-03-01 13:59 UTC
There is a problem with listings related with name tag item.

As you can see there are two schemas that has item name = Name Tag.

For backpack.tf defindex is 2093
For sku is 5020

So when bot is updating listings and try to check stock for name tag, is looking for sku 2093;6. Found 0 and still buying name tag even if is already stocked.

This a mostly a bug from backpack.tf.

**Comment by Nicklason** [comment] 2020-03-01 20:00
I have seen this before but it should not be a problem because I fixed it in the bptf-listings module, let me have a look just to be sure.

**Comment by idinium96** [comment] 2020-03-01 23:48
Yes. My bot encountered this problem, where dozens of trades made for Name Tag were declined. I then do `!remove item=Name Tag` and then add it back with the correct SKU,
`!add sku=5020;6&min=0&max=1`
![nametag](https://user-images.githubusercontent.com/47635037/75636482-296c5900-5c5a-11ea-9799-01317591cf75.PNG)

**Comment by Nicklason** [comment] 2020-03-04 15:24
I think this is just a problem with you not picking the correct defindex for the item, backpack.tf uses 2093 which is incorrect, the correct defindex is 5020. The bot should not have a problem with listings because it looks for matching names and not skus.

@Atosito Can you please confirm that you added the item to the pricelist with the defindex 2093?

**Comment by Nicklason** [comment] 2020-03-09 18:10
Closing because @idinium96 had the same problem and it was caused by picking the wrong defindex.

**Closed by Nicklason** 2020-03-09 18:10 UTC
Labels: bug, question
