### ISSUE TITLE
error: An error occurred while initializing the packages: tf2-prices (Unauthorized).

### ISSUE THREAD

**Issue by HackerinoS2** [Nicklason/tf2-automatic#3] opened 2018-06-17 11:15 UTC
![image](https://user-images.githubusercontent.com/39498755/41507308-1fa2e84e-7228-11e8-9e46-7e2f3e4249c2.png)

**Comment by Waflson** [comment] 2018-06-18 09:29
You most likely need an API key from Nicklason.

**Comment by HackerinoS2** [comment] 2018-06-18 11:38
Oh, so the bot is private?

**Comment by Waflson** [comment] 2018-06-18 13:45
Pretty much. Contact Nicklason if you are looking to purchase it

**Comment by Zulivan** [comment] 2018-06-20 09:00
The bot is free,
The api is premium.
You need to buy an api key to make the bot work :100:

**Comment by Nicklason** [comment] 2018-06-21 16:42
Duplicate of #1

**Closed by Nicklason** 2018-06-21 16:42 UTC

**Comment by Jerseyetr** [comment] 2018-07-27 07:50
Im having this same issue... so you have to purchase the bot?

**Comment by Waflson** [comment] 2018-07-27 08:05
You need to purchase access to the api
