### ISSUE TITLE
Access denied after initializing bptf listing on startup

### ISSUE THREAD

**Issue by danman5542** [Nicklason/tf2-automatic#410] opened 2020-04-02 02:53 UTC
I keep getting this error when I try to start up the bot. I have tried starting it both with and without the BPTF Access Token and API key. Doesn't work either way, though the error appears slightly different. Here it is with the token and key:

2020-04-01 22:45:37 info: Initializing bptf-listings...
Unhandled rejection Error: Access Denied
    at SteamCommunity.<anonymous> (C:\Users\danma\Desktop\tf2-automatic\node_modules\steamcommunity\components\webapi.js:15:20)
    at Request._callback (C:\Users\danma\Desktop\tf2-automatic\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\danma\Desktop\tf2-automatic\node_modules\request\request.js:185:22)
    at Request.emit (events.js:305:20)
    at Request.<anonymous> (C:\Users\danma\Desktop\tf2-automatic\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:305:20)
    at Gunzip.<anonymous> (C:\Users\danma\Desktop\tf2-automatic\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:411:28)
    at Gunzip.emit (events.js:317:22)
    at endReadableNT (_stream_readable.js:1215:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

2020-04-01 22:45:40 info: Getting Steam API key...
2020-04-01 22:45:41 error: tf2-automatic failed to start properly, this is most likely a temporary error. See the log:
package.version: 3.3.10; node: v13.5.0 win32 x64}
Stack trace:
Error: Access Denied
    at SteamCommunity.<anonymous> (C:\Users\danma\Desktop\tf2-automatic\node_modules\steamcommunity\components\webapi.js:15:20)
    at Request._callback (C:\Users\danma\Desktop\tf2-automatic\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\danma\Desktop\tf2-automatic\node_modules\request\request.js:185:22)
    at Request.emit (events.js:305:20)
    at Request.<anonymous> (C:\Users\danma\Desktop\tf2-automatic\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:305:20)
    at Gunzip.<anonymous> (C:\Users\danma\Desktop\tf2-automatic\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:411:28)
    at Gunzip.emit (events.js:317:22)
    at endReadableNT (_stream_readable.js:1215:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Any help would be great

**Comment by idinium96** [comment] 2020-04-02 02:56
Please join tf2-automatic discord server and search "access denied". You'll find the answer for that problem.

https://discord.tf2automatic.com/

**Comment by aethezxd** [comment] 2020-04-02 08:16
If i recall correctly this is because the account is not premium, meaning that the account has not spent at least $5 on Steam.

**Comment by HunionKnight** [comment] 2020-04-02 08:22
@aethezxd Is correct. That is the cause of Access Denied.
 In future please join tf2-automatic discord server and search for your problem before creating an issue. You'll find an answer for 99% of problems and save yourself time waiting for a reply.

https://discord.tf2automatic.com/

-closing-

**Closed by HunionKnight** 2020-04-02 08:22 UTC
